version: "3.9"

services:
  redis:
    image: redis
    restart: always

  postgres_db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=django_db_users
    ports:
      - "5432:5432"

  django:
    restart: always
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    command: bash -c "python ./support/manage.py makemigrations && python ./support/manage.py migrate && python ./support/manage.py runserver 0.0.0.0:8000"

#  worker:
#    restart: always
#    build:
#      context: ./
#    volumes:
#      - ./
#    command: ["celery", "--workdir=./support", "-A", "./support", "worker"]

