version: "3.9"

services:
  redis:
    image: redis
    restart: always

  postgres_db:
    image: postgres:14.0-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - "5432:5432"

  django:
    restart: always
    build:
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db

#  worker:
#    restart: always
#    build:
#      context: ./
#    volumes:
#      - ./
#    command: ["celery", "--workdir=./support", "-A", "./support", "worker"]

